#[path = "./mod.rs"]
pub mod erc20;

use pevm::serialization::{serializer, deserializer, adapter};

use std::fs::File;
use std::io::{self, BufRead, BufReader, Write};
use std::path::Path;

pub async fn generate_workload() -> Result<(), Box<dyn std::error::Error>> {
    let file_path = "test_output.txt";
    const NUM_CLUSTERS: usize = 1;
    const NUM_FAMILIES_PER_CLUSTER: usize = 15;
    const NUM_PEOPLE_PER_FAMILY: usize = 15;
    const NUM_TRANSFERS_PER_PERSON: usize = 15;
    for _ in 0..NUM_CLUSTERS {
        let (state, bytecodes, txs) = erc20::generate_cluster(NUM_FAMILIES_PER_CLUSTER, NUM_PEOPLE_PER_FAMILY, NUM_TRANSFERS_PER_PERSON);
        println!("Generated bytecodes: {:?}", bytecodes);
        for tx_env in txs {
            // println!("Original TxEnv: {:#?}", tx_env);
            serializer::write_to_file(tx_env, file_path).await?;
            // let batch = deserializer::read_from_file(file_path)?;
            // // println!("Read from file: {:#?}", batch);

            // let result = deserializer::decode_batch_hex(batch);
            // // println!("Decoded Results: {:#?}", result);
        }

    }
    Ok(())
}

/// Distributes lines from `input_path` into `n` output files round-robin.
/// The x-th line is written to the (x % n)-th output file.
pub fn split_file_round_robin<P: AsRef<Path>>(input_path: P, n: usize) -> io::Result<()> {
    if n == 0 {
        return Err(io::Error::new(io::ErrorKind::InvalidInput, "n must be > 0"));
    }

    // Open input file
    let input_file = File::open(&input_path)?;
    let reader = BufReader::new(input_file);

    // Prepare output files
    let mut writers: Vec<Box<dyn Write>> = Vec::with_capacity(n);
    for i in 0..n {
        let filename = format!("output_{}.txt", i);
        let file = File::create(filename)?;
        writers.push(Box::new(file));
    }

    // Distribute lines round-robin
    for (i, line) in reader.lines().enumerate() {
        let line = line?;
        let target_index = i % n;
        writeln!(writers[target_index], "{}", line)?;
    }

    Ok(())
}